spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: classpath:logbook.yml
  application:
    name: rikser-crawler
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: rikser-crawler
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "rikser-crawler"
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: rikser-crawler
    liquibase-schema: rikser-crawler
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: crawler
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms

server:
  port: 8081

bundle:
  security:
    enabled: true
    service:
      enabled: true
      url: ${SECURITY_URL}
  redis:
    TTL: P1D
    prefix: yandex-query
    enabled: true
  kafka:
    enabled: true
    user: ${KAFKA_USER}
    password: ${KAFKA_PASSWORD}
    kafka-url: ${KAFKA_URL}
    max-fetch-limit: 200

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    health:
      show-details: always
      status:
        http-mapping:
          down: 503

logbook:
  predicate:
    exclude:
      - path: /api/v1/user/public-key
      - path: /actuator/**

fetch:
  queue-limit: ${QUEUE_LIMIT:50}
  timeout-queue-limit: ${TIMEOUT_QUEUE_LIMIT:50}
  max-download-attempt: ${MAX_DOWNLOAD_ATTEMPT:3}
  repeat-download-delay: ${REPEAT_DOWNLOAD_ATTEMPT:3}
  max-body-size: ${MAX_BODY_SIZE:1 024 000}
  chunk-size: ${CHUNK_SIZE:2000}
  word-overlap-count: ${WORD_OVERLAP_COUNT:200}

kafka:
  scheduler-delay: PT10S

rest:
  connection-timeout: 5
  read-timeout: 10

bothub:
  token: ${BOTHUB_TOKEN}
  url: ${BOTHUB_URL}
  summary_model: ${BOTHUD_SUMMARY_MODEL:deepseek-v4-flash}
  analysis_model: ${BOTHUD_ANALYISIS_MODEL:deepseek-v4-pro}
  timeout: ${BOTHUB_CONNECTION_TIMEOUT:60}

